
const fsPath = require('fs-path');
const fs = require('fs');
const utils = require('../../utils');

async function updateGitignore(cwd) {
  const gitIgnorePath = `${cwd}/.gitignore`;
  const nodeModulesIgnoreStr = '\n#node_modules\nnode_modules\n';
  const functionsIgnoreStr = '\n#sm main functions\nsm.functions.yml\n';
  const slsIgnoreStr = '\n#servelees file generated by build\nsrc/**/serverless.yml\n';
  const fullGitIgnoreStr = `${nodeModulesIgnoreStr}${functionsIgnoreStr}${slsIgnoreStr}`;
  if (!utils.fileExits(gitIgnorePath)) {
    fsPath.writeFileSync(gitIgnorePath, fullGitIgnoreStr);
  } else {
    if (!utils.existsInFile('node_modules', gitIgnorePath)) {
      fs.appendFileSync(gitIgnorePath, nodeModulesIgnoreStr);
    }
    if (!utils.existsInFile('sm.functions.yml', gitIgnorePath)) {
      fs.appendFileSync(gitIgnorePath, functionsIgnoreStr);
    }
    if (!utils.existsInFile('src/**/serverless.yml', gitIgnorePath)) {
      fs.appendFileSync(gitIgnorePath, slsIgnoreStr);
    }
  }
}

module.exports = {
  updateGitignore
};
